/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_android_ErlangThread */

#ifndef _Included_com_couchbase_android_ErlangThread
#define _Included_com_couchbase_android_ErlangThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_android_ErlangThread
 * Method:    start_erlang
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_android_ErlangThread_start_1erlang
  (JNIEnv *, jclass, jstring, jstring, jobjectArray);

/*
 * Class:     com_couchbase_android_ErlangThread
 * Method:    send_bin
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_android_ErlangThread_send_1bin
  (JNIEnv *, jclass, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
